// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

// Load Roboto for global use
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // You can add more weights if needed
  display: "swap",
});

export const metadata: Metadata = {
  title:
    "Asthiamrit Herbal Oil - Premium Ayurvedic Pain Relief Oil | Natural Joint & Muscle Pain Treatment",
  description:
    "Asthiamrit Herbal Oil - India's #1 Ayurvedic pain relief oil with 20+ natural herbs. Fast relief from arthritis, back pain, knee pain & muscle soreness. AYUSH certified. Free shipping.",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply Roboto font globally */}
      <body className={`${roboto.className} antialiased`}>{children}</body>
    </html>
  );
}
